### ISSUE TITLE
Webpage prints to A4 dimensions rather than Letter

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#105]
See for example this [Sci-Hub Manuscript PDF](https://github.com/greenelab/scihub-manuscript/blob/0c2aaa075280c8f7b3895a5892768ad474d4c894/manuscript.pdf). The Paper Size according to the PDF's properties is A4, Portrait (8.26 × 11.68 inch). This caused an [issue](https://github.com/greenelab/scihub-manuscript/pull/51#issue-293357705) when I printed the PDF where some final lines on a page were omitted.

This [StackOverflow](https://stackoverflow.com/a/29836423/4651668) notes how to change the page to Letter (8.5 × 11). I just want to confirm this is a change we want to make. I didn't realize there were multiple paper sizes, both prevalent, in this unstandardized world!

**Comment by dhimmel** [comment]
Some references:

+ [Letter vs A4 paper: are you using the right size?](https://indiesew.com/blog/letter-vs-a4-paper-are-you-using-the-right-size
+ [Letter or A4: which is a more sensible default?](https://graphicdesign.stackexchange.com/q/38904)

**Comment by dhimmel** [comment]
Also is this something that we should address, or should my printer / print settings be smart enough to shrink the A4 to fit on the Letter paper? Is there a standard for scholarly PDFs?

**Comment by agitter** [comment]
I thought this was standard, but then I spot checked a few journal article PDFs and found many that are 8.5 x 11 and others that were 8.27 x 10.87 or 8.37 x 10.87.  Letter feels standard to me because I'm US-based.  Changing to letter by default seems okay.  In the usage we can note or link to instructions for setting it back to A4.

Changing paper size is simple and fairly common [in LaTeX](https://www.sharelatex.com/learn/Page_size_and_margins).
