### ISSUE TITLE
nan (missing) author fields

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#15]
Quoting from https://greenelab.github.io/scihub-manuscript/

> 0000-0002-9925-9623 · Department of Applied Bioinformatics, Institute of Cell Biology and Neuroscience, Goethe University Frankfurt · Funded by nan

Would be better to have jinja2 omit blank fields entirely. In other words remove " · Funded by nan"

**Comment by vsmalladi** [comment]
Should be able to update 00.front-matter.md to be conditional on fields.

**Comment by dhimmel** [comment]
> Should be able to update 00.front-matter.md to be conditional on fields.

Yep. want to submit a PR?

**Comment by vsmalladi** [comment]
Ya I can do that. Just testing the code locally.

**Comment by vsmalladi** [comment]
Are there any fields you want required?
 I was thinking:
 

- github_username
- full_name	
- initials	
- orcid
- email

**Comment by dhimmel** [comment]
> Are there any fields you want required?

What does required mean? Enforced in the source code or just always displayed even if blank?

As far as truly required, probably name and initials only. But I'm mostly concerned about fixing the output, rather than automating checks that PR review should catch. Different projects will have different needs when it comes to this metadata.

**Comment by vsmalladi** [comment]
Okay that makes sense. I will just have Name and inititals present then otherwise if blank don't display.

**Comment by slochower** [comment]
This PR seems to create a references warning for me. I believe the the code here works and the code to detect a malformed reference should be adjusted, but I admit I haven't had time to check yet. I'm also not sure why this didn't pop up on Travis CI here, but did for my fork (perhaps because of the different entries in `authors.tsv`).

![image](https://user-images.githubusercontent.com/5393995/28236002-a78b2b30-68cf-11e7-98d9-01df6f02bff9.png)

**Comment by dhimmel** [comment]
Yeah, I noticed this too. The builds come out fine... we should relax the malformed reference detection. Or entirely remove it if we pursue #2.
