### ISSUE TITLE
PDF formatting is not ideal

### ISSUE THREAD

**Issue by slochower** [greenelab/manubot-rootstock#20]
In several places, the PDF rendering looks (subjectively) worse than the HTML output. (I'm not sure if I'll have time to work on this during the week, but I wanted to drop this here in case someone else has time before me.)

- Overall, I think the margins of the PDF could be adjusted. The relatively short title already wraps in the PDF.

- There are places where the HTML has spaces between the text and the references, but the PDF output does not. I'm not sure why this happens.

- Code style could be formatted as monospaced in the PDF output.

- Tables look much better in HTML than PDF (shading and banding).

- The SVG example figure is missing (known problem: #14).

**Comment by dhimmel** [comment]
@slochower in https://github.com/greenelab/manubot-rootstock/commit/1ad485b9b61759edeafbc6bae36b07e97c75433e we switched from using pandoc to create the PDF, to directly creating it from the HTML using [`wkhtmltopdf`](https://wkhtmltopdf.org/). See discussion at https://github.com/greenelab/manubot-rootstock/pull/18#issuecomment-315559705.

Take a look at the new PDFs. (will update here, they're not online yet due to bug in #19).

**Comment by slochower** [comment]
Regarding the discussion in #18 -- and the general aesthetics of the PDF -- I think my main concern is how customizable the PDF will be to comply with specific demands made by journals. For example, if they say that section headers need to be 12 point bold font and the body text needs to be 12 point Times New Roman (or worse: use a specific style that's only accessible inside some Word 2010 template), my questions are (a) will we be able to do that, and if so (b) will that happen before HTML generation or between the HTML and PDF or somewhere else in the pipeline. I'm not suggesting this project needs to work for all user scenarios, I'm just curious about your thoughts. 

As far as I'm concerned, the HTML is nice for reading but the PDF will probably be uploaded to journals or what is submitted for reviews,  agreeing with https://github.com/greenelab/manubot-rootstock/pull/18#issuecomment-315559705.

**Comment by dhimmel** [comment]
> how customizable the PDF will be to comply with specific demands made by journals

Let's start with the assumption that a PDF itself is not customizable at all once generated. Therefore all customization has to occur at an earlier stage... either the HTML display or thought an intermediate renderrer such as LaTeX or a word processor.

In the case of draconian journal formatting requirements, here's how I would approach it:

1. Consider whether the journal is unjustly terrorizing you. Is there a functional deficit to the default PDF format of the manubot? Is this PDF just for review, hence formatting doesn't really matter. If so consider not complying with the journal guidelines if you deem them antiquated and counterproductive. You're providing the journal with important customer feedback that their system has uneccessary inneficiencies. PDF formatting requirements make little sense in general because PDFs are not machine-readable. Hence, nothing is going to break if a PDF isn't formatted in a certain way.

2. Consider how many times you will have to make the style changes. If only once or twice for a specific journal that may not even accept it, consider just copying the rendered HTML to a word processor as rich text. Then update the styles in the word processor. Using this method, you should be able to comply with almost any requirements in ~1 hour of manual labor.

3. If you need to reproducibly and automatically generate a PDF with a specific format, then the ideal solution would be to modify `github-pandoc.css`. In the future and if this project grows, one could imagine that each journal/publisher produces their own CSS style, as has been done with [CSL styles](https://github.com/citation-style-language/styles). For the time being, using pre-existing LaTeX styles for a journal may be the easiest solution. However, this requires exporting the manuscript to LaTeX and I think this will be a lossy export in many cases.

@slochower does this help answer your question. I guess the big difference in my philosophy from others here is that I think submission PDFs will often be created manually or using print to PDF. Therefore, to me the PDFs tracked in `gh-pages` are mostly there as standalone testaments to the manuscript version at a past time. The other main benefit to PDFs over the HTML is that they provide a portable print format. So if we want many users printing the manuscript and having the exact same layout, a standard PDF is important.

**Comment by vsmalladi** [comment]
@dhimmel the PDF looks much better.

Additionally I agree, the PDF is a good version to pass around for collaborators to print and read and provide feedback. I don't think it would be too hard to make final changes in a word processor to comply with the specific Journal requirements. I already have to do this manually and this doesn't take too much time at all.

**Comment by slochower** [comment]
@dhimmel I largely share the same philosophy but have encountered obstacles that weren't worth fighting.

> If only once or twice for a specific journal that may not even accept it, consider just copying the rendered HTML to a word processor as rich text. Then update the styles in the word processor. 

If I paste the HTML output in Word, everything is rendered with the "Normal" style, just with a different font. 
![image](https://user-images.githubusercontent.com/5393995/28250501-19fa0394-6a1f-11e7-8242-ded6eab0f631.png)
So I think it could take some manual labor to change the titles and headings and so forth to meet journal criteria. Moreover, things like line numbering, page numbering, and section breaks can lead to unexpected results (especially when going through Word, in my experience), and it'd be nice to not have to deal with these problems more than once or twice. This gets to the second point, which is reproducibility. 

(There are additional weird quirks that happen when doing this, e.g., the hyperlinks in the Word version -- and thus, the exported PDF -- will point to the latest HTML page.)
<img width="444" alt="screen shot 2017-07-16 at 12 16 09 pm" src="https://user-images.githubusercontent.com/5393995/28250554-44e5fd0a-6a20-11e7-99af-2f11420db9c8.png">

> If you need to reproducibly and automatically generate a PDF with a specific format, then the ideal solution would be to modify `github-pandoc.css`.

If going through HTML is the preferred the pipeline, then this sounds right to me, but it does add new complexity (or maybe I should say sophistication) for the user.

I'm not suggesting any changes at the moment, and I do think the new PDF looks good, and I also agree that HTML is preferred. I'm hoping I won't have to deal with too much manual PDF formatting in the future.

**Comment by dhimmel** [comment]
> the hyperlinks in the Word version -- and thus, the exported PDF -- will point to the latest HTML page

Agreed this is a problem. Perhaps it's worth looking into HTML to `docx` converters... or seeing if we can use pandoc to export to docx.

> So I think it could take some manual labor to change the titles and headings and so forth to meet journal criteria

I'm not a word processor expert, but you should be able to define a style... like all h1 headers appear as such.

> I'm not suggesting any changes at the moment, and I do think the new PDF looks good, and I also agree that HTML is preferred. I'm hoping I won't have to deal with too much manual PDF formatting in the future.

Thanks for your feedback. It will be helpful to get some case reports of how the entire journal interaction played out for a manuscript built from this system. Once we get a better idea of the pain points, then we can optimize. My understanding is that a word document is generally only needed for the final submission? So there may be no one who has actually had to deal with this yet? @agitter how did submission work with the Deep Review?

**Comment by vsmalladi** [comment]
>  Perhaps it's worth looking into HTML to docx converters... or seeing if we can use pandoc to export to docx.

@dhimmel pandoc does have the a converter to docx that i am playing around with. I will see wht formatting i can get done using it.

**Comment by agitter** [comment]
> I'm not a word processor expert, but you should be able to define a style... like all h1 headers appear in font X with size Y.

I tested this in Word 2013, and it worked well.  I copied and pasted the HTML into a blank document.  I selected a level 3 header (`Equations`) and then `Select Text with Similar Formatting`:

![image](https://user-images.githubusercontent.com/3532898/28251209-e2a75efe-6a3d-11e7-9c6c-9fda4382919a.png)

Then I applied the Heading 3 style to the selected text.  All level 3 headers are associated with that style and update when I modify the style: 

![image](https://user-images.githubusercontent.com/3532898/28251221-43216752-6a3e-11e7-91d9-d52e9d5c1115.png)

> hyperlinks in the Word version -- and thus, the exported PDF -- will point to the latest HTML page

I agree this is a problem.  Thanks for looking at docx conversion @vsmalladi, that may provide the best solution.  A temporary workaround could be to use `sed` to remove the anchor links within the document before copying and pasting into Word.  As long as the numbering is correct, I don't think journals care about links.

@dhimmel For deep review, @cgreene made the journal submission.  I believe he submitted the exact same PDF he posted to bioRxiv.  That may have been a special case because it was an invited review.  I'm also aware of desk rejections due to misformatted manuscripts.

I'm optimistic that bioRxiv will continue to influence biology journal attitudes about initial submissions.  Currently, many do have strict formatting requirements.  But those journals that support direct submission from bioRxiv have agreed that a human-readable manuscript is what is most important initially.  We just need to ensure there is at least one path to a Word or LaTeX document for the final submission that doesn't require unreasonable manual effort.

In general, I think that LaTeX with continuous analysis may be a better choice than this system for some types of manuscripts.  For other types (e.g. the deep review with no equations and 20+ collaborators), this system was great.

Once this build system matures, we may want to solicit a friendly journal editor or two for feedback.

**Comment by slochower** [comment]
> I tested this in Word 2013, and it worked well. I copied and pasted the HTML into a blank document. I selected a level 3 header (Equations) and then Select Text with Similar Formatting:

Interesting. This helps a lot! I don't think `Select Text with Similar Formatting` feature is available on the macOS versions though.

**Comment by vsmalladi** [comment]
I started some tests with docx formatting and made a pull-request we can have a discussion in #26

**Comment by dhimmel** [comment]
@slochower I think these issues are now resolved. For example, see the latest [Deep Review PDF](https://github.com/greenelab/deep-review/blob/cb0e1dd68851a33f719ba7105aa5300c4475df3b/manuscript.pdf).

If there are any remaining problems, please open new issues!

**Comment by slochower** [comment]
Much better, @dhimmel.
