### ISSUE TITLE
Setup commands fail on macOS

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot-rootstock#74]
Some of the commands in [SETUP.md](https://github.com/greenelab/manubot-rootstock/blob/3a42f6bd45fad874b29898cc744caf0ed23437af/SETUP.md) fail on macOS. IIRC, these commands are:

```sh
TRAVIS_ENCRYPT_ID=`grep \
  --only-matching --perl-regexp \
  --regexp='(?<=encrypted_)[a-zA-Z0-9]+(?=_key)' \
  travis-encrypt-file.log`
sed --in-place "s/f2f00aaf6402/$TRAVIS_ENCRYPT_ID/g" deploy.sh
```

```sh
sed --in-place "s/greenelab/$OWNER/g" README.md
sed --in-place "s/manubot-rootstock/$REPO/g" README.md
```

The issue is likely that the mac versions of these utilities don't support the same long arguments. What a shame.

**Comment by dhimmel** [comment]
We could force mac users to switch their default `sed` and `grep` binaries to the GNU versions:

```sh
brew install gnu-sed --with-default-names
brew install grep --with-default-names
```

**Comment by vsmalladi** [comment]
Testing on a mac and having homebrew helps fix some of the missing libraries:
cairo
pango

**Comment by dhimmel** [comment]
> Testing on a mac and having homebrew helps fix some of the missing libraries

Are you saying that the conda environment installed on macOS but even then there were missing libraries?

Also `cairo` and `pango` are not relevant at the setup stage. This is for configuring a new manubot instance... before the conda environment is even installed.

Although you do potentially raise an interesting point. We do the SETUP commands in the conda environment to get consistent versions of [`sed`](https://anaconda.org/conda-forge/sed) and [`grep`](https://anaconda.org/bioconda/grep) (linux and macOS). However, I'm not sure it's worth requiring conda for setup... right now its just needed to build.

**Comment by agitter** [comment]
@dhimmel are you thinking we would include sed and grep in `environment.yml` or just recommend the conda versions for Mac users?  A simple solution would be to add a troubleshooting section at the bottom of `SETUP.md`.  We can provide a sample `sed` call so that Mac users can test if they have a version that supports the required long arguments.  If not, we can show them how to install the GNU versions from brew or conda.

> Or perhaps we could make a setup script that runs in a docker image?

That is also appealing because of the Travis command line client.  My favorite old Linux machine didn't have the right dependencies so I ended up running the travis client in a Docker container.  I'm not sure what fraction of users will be Docker-savvy, but if we have a container it wouldn't be required.

To really break through to a wide audience with no computational background might require something that is almost fully automated.  Could a GitHub App be granted access to a user's account and setup a new manuscript repository with the desired name?  I haven't thought through the technical requirements and it seems low priority.  However, if that worked, users could do all manuscript writing through the GitHub web interface and be completely free of the local computing environment.

**Comment by vsmalladi** [comment]
@agitter Docker would be nice. 

I can do some tests on my mac to setting up. I am going to start writing a paper using the current build on a mac and could update documentation to help troubleshooting on a mac.

**Comment by vsmalladi** [comment]
Okay some workout around on setting up on mac.

## Deploy Key (MAC OSX)
```sh
# Edit ci/deploy.sh with travis secure env variables generated by travis encrypt-file
TRAVIS_ENCRYPT_ID=`sed \
    -n 's/.*encrypted_\(.*\)_key.*/\1/p' \
    travis-encrypt-file.log`
sed -i '' "s/f2f00aaf6402/$TRAVIS_ENCRYPT_ID/g" deploy.sh
```

##  README updates (MAC OSX)
```sh
sed -i '' "s/greenelab/$OWNER/g" README.md
sed -i '' "s/manubot-rootstock/$REPO/g" README.md
```

**Comment by vsmalladi** [comment]
@dhimmel @agitter Should i make a pull request to add these workarounds for mac?

**Comment by agitter** [comment]
@vsmalladi a pull request seems like a good idea to me.  We can finish the discussion there, but before merging the pull request I would suggest we verify:
- The Mac workaround you propose also works in Linux, in which case we can have a single set of cross-platform commands, OR
- Another user can confirm that the workaround works for them on Mac OS
