### ISSUE TITLE
Bake hypothesis into the HTML versions of the manuscripts

### ISSUE THREAD

**Issue by RaoOfPhysics** [greenelab/manubot-rootstock#90]
Add:

```html
<script src="https://hypothes.is/embed.js" async></script>
```

Doesn't work natively with the PDF files, sadly.

**Comment by dhimmel** [comment]
Some links:

+ https://web.hypothes.is/publishing/
+ https://h.readthedocs.io/projects/client/en/latest/publishers/embedding/

> Doesn't work natively with the HTML files, sadly.

You mean that it requires javascript? The upside is that it will be super easy to implement.

We can add it to a file that Pandoc will put insert into the HTML just like [how we](https://github.com/greenelab/manubot-rootstock/blob/64af604e7987bc51b11cac123c6c178201fbaccd/build/assets/analytics.js) insert analytics javascript.

My initial feeling is that we'd enable this for the HTML manuscript only. @RaoOfPhysics any idea how well this works when the HTML page changes? Is it possible to see comments that are presently detached because the text has changed?

**Comment by RaoOfPhysics** [comment]
@dhimmel: Ugh, I meant PDF files, not HTML files. It works just fine with HTML. Edited my OP to reflect this.

**Comment by RaoOfPhysics** [comment]
> Is it possible to see comments that are presently detached because the text has changed?

Yes!

**Comment by dhimmel** [comment]
We can see how the hypothesis version will behave using their "Paste a link" feature. For example, see https://via.hypothes.is/https://greenelab.github.io/scihub-manuscript/. One issue is that the hypothesis page seems to appear when printing the website. However, we [create the PDF](Will look into whether it appears when exporting the PDF using Pandoc and WeasyPrint.) using Pandoc/WeasyPrint, and we don't have to add hypothesis here.

**Comment by RaoOfPhysics** [comment]
Highlighting any text to annotate it pulls up the dialogue box far away from the text itself:

<img width="1189" alt="firefox - - screen shot 29 nov 2017 at 10 00 35" src="https://user-images.githubusercontent.com/7623019/33366676-3b95c0dc-d4ec-11e7-98e8-e71812fe7dbe.png">

I wonder if this is an issue with Hypothesis itself or if some JS from the manuscript page is causing this to behave strangely?

**Comment by RaoOfPhysics** [comment]
@dhimmel: I still see a displaced dialogue box on https://via.hypothes.is/https://greenelab.github.io/scihub-manuscript/ I'm guessing the changes from this PR haven't been propagated there yet?

**Comment by dhimmel** [comment]
> I'm guessing the changes from this PR haven't been propagated there yet?

Yeah, new changes have to be manually merged in as [described here](https://github.com/greenelab/manubot-rootstock/blob/f165f609f33b11fdf71a0db6435d4dd159f23973/SETUP.md#merging-upstream-manubot-rootstock-changes).
